expname: init_from_more

data:
  data_dir: ./20_fps

  #=========
  N_rays: 1024
  downscale: 4.
  #=========

model:
  framework: SirenNeRF
  net_w: 128
  # nerf-minus-minus
  so3_representation: 'axis-angle'
  # siren
  siren_sigma_mul: 10.0 # multiply the raw_sigma output of SirenNeRF
  siren_first_layer_w0: 30.0
  siren_following_layers_w0: 1.0

training:
  ckpt_file: ./logs/more_diff_pics_scratch/ckpts/latest.pt
  exp_dir: ./logs/init_from_more
  # learning rate anneal
  step_size_nerf: 10    # unit: epochs
  lr_anneal_nerf: 0.9954 #0.9954
  lr_nerf: 9.945724111795075e-06

  step_size_param: 100  # unit: epochs
  lr_anneal_param: 0.9
  lr_param: 2.951266543065282e-08
  num_epoch: 10000
  novel_view_synthesis: false  # whether do novel view synthesis during traning