expname: doll_our_cam

data:
  data_dir: ./20_fps

  #=========
  N_rays: 1024
  downscale: 4.
  #=========

model:
  framework: SirenNeRF
  net_w: 128
  # nerf-minus-minus
  so3_representation: 'axis-angle'
  # siren
  siren_sigma_mul: 10.0 # multiply the raw_sigma output of SirenNeRF
  siren_first_layer_w0: 30.0
  siren_following_layers_w0: 1.0

training:
  # learning rate anneal
  step_size_nerf: 10    # unit: epochs
  lr_anneal_nerf: 0.5 #0.9954
  lr_nerf: 1.0e-04

  step_size_param: 100  # unit: epochs
  lr_anneal_param: 0.5
  lr_param: 5.0e-04
  num_epoch: 10000

  novel_view_synthesis: false  # whether do novel view synthesis during traning