data:
  N_rays: 1024
  batch_size: null
  data_dir: ./data/castle_1041
  downscale: 4.0
  far: 1.0
  near: 0.0
  white_bkgd: false
device_ids:
- 0
expname: nerfmm_castle_1041
model:
  N_importance: 0
  N_samples: 128
  framework: NeRF
  initial_fov: 53.13
  intrinsics_representation: square
  multires: 10
  multires_views: 4
  net_d: 8
  net_d_fine: null
  net_skips:
  - 4
  net_skips_fine: null
  net_w: 128
  net_w_fine: null
  netchunk: 524288
  perturb: 1.0
  raw_noise_std: 1.0
  rayschunk: 131072
  so3_representation: axis-angle
  use_fine_model: false
  use_viewdirs: true
  val_rayschunk: 32768
  sigma_clamp_mode: relu
training:
  ckpt_file: null
  ckpt_ignore_keys: []
  exp_dir: logs/nerfmm_castle_1041/
  i_backup: 50000
  i_save: 900
  log_root_dir: logs
  lr_anneal_nerf: 0.9954
  lr_anneal_param: 0.93
  lr_nerf: 0.001
  lr_param: 0.001
  no_reload: false
  novel_view_synthesis: false
  num_epoch: 10000
  step_size_nerf: 10
  step_size_param: 100
  w_img: 1.0
  w_perceptual: 0.0
